### ISSUE TITLE
Validator compliance with JSON Schema?

### ISSUE THREAD

**Issue by alexweissman** [mcustiel/php-simple-request#1]
Would you consider making the validation filters compliant with the [JSON Schema](http://json-schema.org/latest/json-schema-validation.html) definitions?

**Comment by mcustiel** [comment]
Great idea. 
When I created the filters I just started by creating some as examples for myself, but never thinking of some standard, being compliant with json schema could improve this library.
I can't implement it in the short term because I'm moving to Germany in 2 weeks and I'm really busy. Maybe next month I could start working on it. Thanks for the idea, Alex!

**Comment by alexweissman** [comment]
Cool!  Yeah, it seems like form validation/sanitization is a wheel that gets reinvented quite often in PHP - I like the concept of having a library to do this, and decoupling the rules from the code ;-)

Good luck in Germany!

**Comment by mcustiel** [comment]
Working on it...

**Comment by mcustiel** [comment]
Version 1.1.0 has the new validations.
